### ISSUE TITLE
How to define  “bioactivity values” ?

### ISSUE THREAD

**Issue by Bigrock-dd** [cansyl/DEEPScreen#10]
“we constructed positive (active) and negative (inactive) training datasets as follows: for each target, compounds with bioactivity values ≤10 μm were selected as positive training samples...”
Could you please explain how to define "bioactivity values"？
Looing forward to your reply！

**Comment by tuncadogan** [comment]
Hi, these experimental bioactivity values are directly obtained from the ChEMBL database (https://www.ebi.ac.uk/chembl/). We downloaded and filtered those bioactivity data points as explained in the methods section of our paper. Let me know if you have further questions.
