### ISSUE TITLE
training model _ another species

### ISSUE THREAD

**Issue by RN-Taka** [cansyl/DEEPScreen#11]
Hi,
if i have interactions (Drugs-targets) with other organisms (not human), is it possible to run the training model?
or it is specific for human?

thank you!

**Comment by tuncadogan** [comment]
Hi, yes it is possible, in fact, some of the targets that we prepare datasets for are non-human proteins. The important point here is that target protein should have a decent number of interacting/non-interacting ligand data points in the source bioactivity databases.
