### ISSUE TITLE
New compound prediction - not in CHEMBL and doesn't have a CHEMBL_ID

### ISSUE THREAD

**Issue by vaish-navii** [cansyl/DEEPScreen#14]

**Comment by vaish-navii** [comment]
The same error occurs even when I don't add a new compound and just try to run a different target.

**Comment by ahmetrifaioglu** [comment]
Dear @vaish-navii , 

Thanks for your interest in DEEPScreen and sorry for the late reply. It is hard to resolve the problem this way but it seems that the img_arr object has None value which means that images were not properly read. Could you please check if those images in the correct path?

**Comment by vaish-navii** [comment]
Thank you for your reply. After your comment, I began digging into the problem. I think I found out what it was. I was using generic RDKit code to generate images of new molecules without specifying some of the parameters mentioned in the paper. As soon as I corrected it, they began working fine. You were right about the images not being read correctly. I suspected it, but was unsure about the exact issue.

Your guidance was super helpful! Thank you very much.
