### ISSUE TITLE
UnboundLocalError: local variable 'best_test_performance_dict' referenced before assignment

### ISSUE THREAD

**Issue by hmkim** [cansyl/DEEPScreen#6]
Hi!

`python main_training.py --targetid CHEMBL286 --model CNNModel1 --fc1 256 --fc2 128 --lr 0.01 --bs 64 --dropout 0.25 --epoch 100 --en my_chembl286_training`

![스크린샷 2020-12-01 오후 3 24 09](https://user-images.githubusercontent.com/4966343/100705286-4c46bc00-33ea-11eb-911d-fba92410c41a.png)

For the tutorial (e.g train step),  I can't run the code normally.
Could you check this, please?

**Comment by tuncadogan** [comment]
Hi, unfortunately, I could not reproduce your error, it is running fine in our tests. Are you following the instructions provided in the readme before executing the command? In which platform you are running the code?

**Comment by hmkim** [comment]
Hi @tuncadogan 

$ conda create -n deepscreen_env python=3.7
$ conda activate deepsceren_env
$ git clone https://github.com/cansyl/DEEPScreen.git
$ cd bin
$ pip install -r requirements.txt 
$ pip install torch==1.7.0+cu101 torchvision==0.8.1+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html # for GPU
$ python main_training.py --targetid CHEMBL286 --model CNNModel1 --fc1 256 --fc2 128 --lr 0.01 --bs 64 --dropout 0.25 --epoch 100 --en my_chembl286_training


 Ubuntu 18.04.4 LTS

**Comment by tuncadogan** [comment]
I checked the problem again given the information, it most probably is related to the additional libraries you install. From the messages:

"There was a problem during training performance calculation!"
"There was a problem during validation performance calculation!"
"There was a problem during test performance calculation!"

it is evident that predictions could not be calculated at all (for any of the epochs), indicating a problem related to torch. Please try again, this time without installing those additional libraries.

**Comment by hmkim** [comment]
![스크린샷 2020-12-08 오전 9 39 13](https://user-images.githubusercontent.com/4966343/101422119-3e88bd80-3939-11eb-9d95-5b2997f09b28.png)

On your guide, there is no problem!

```
conda create -n deepscreen_env python=3.7
source activate deepscreen_env
pip install -r requirements.txt
```

Thank you!
