### ISSUE TITLE
Error for running

### ISSUE THREAD

**Issue by rebirthjin** [cansyl/DEEPScreen#7]
Hello, I'm interesting your work so I try to use a given training model. 
However, I got error message by last epoch. 

Epoch :99
Training mode: True
Epoch 99 training loss: 3.122581034898758
There was a problem during training performance calculation!
Validation mode: True
There was a problem during validation performance calculation!
There was a problem during test performance calculation!
Traceback (most recent call last):
  File "./bin/main_training.py", line 69, in <module>
    args.dropout, args.epoch, args.en)
  File "/home/njgoo/Data1/program/DEEPScreen/bin/train_deepscreen.py", line 184, in train_validation_test_training
    best_val_test_result_fl.write("Test {}:\t{}\n".format(scr, best_test_performance_dict[scr]))
UnboundLocalError: local variable 'best_test_performance_dict' referenced before assignment

Thanks for your reply!

**Comment by tuncadogan** [comment]
Hi, this problem is related to the version of torch libraries. Please create a new environment using the instructions in our readme:

conda create -n deepscreen_env python=3.7
source activate deepscreen_env
pip install -r requirements.txt

Please run DEEPScreen models in this environment. Let me know if you further face an issue.

**Comment by rebirthjin** [comment]
Thank you for quick response.
I had a creation of the new environment but I got the error message!

Is it white space problem at the code?

Please, check the issue, one more time.

Good day!!

**Comment by tuncadogan** [comment]
It is important to follow the instruction exactly. Do you have a previously installed PyTorch in your system?

We had the same issue just a couple of days ago and solved it by uninstalling the previously installed PyTorch and creating the environment as stated. Please see this discussion:

https://github.com/cansyl/DEEPScreen/issues/6

**Comment by rebirthjin** [comment]
Thank you for comment!

Yes, I followed the instruction by readme, exactly.

$ conda create -n deepscreen_env python=3.7
$ conda activate deepsceren_env
$ git clone https://github.com/cansyl/DEEPScreen.git
$ cd bin
$ pip install -r requirements.txt

After I didn't install any library of python in deep_screen_env.

PyTorch version is 1.5.0 and Python 3.7.9 in depp_screen environment.

I will see your link, and compile again!

**Comment by rebirthjin** [comment]
I solve this problem to change evaluation_metrics.py in #3

You could update the file in github!

Thank you for kind.

**Comment by tuncadogan** [comment]
Thank you for the feedback, I'm looking into that.
